version: '3.2'

services:
  portainer:
    image: portainer/portainer-ce
    command: --tlsskipverify
    ports:
      - 9000
    volumes:
      - ~/data/portainer:/data
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
      - ~/.local/share/docker/volumes:/var/lib/docker/volumes
    networks:
      - internal_portainer
      - traefik_public
    labels:
      # traefik
      - traefik.enable=true
      - traefik.docker.network=traefik_public
      # traefikv2
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN:?err}`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  traefik_public:
    external: true
  internal_portainer:
